

import { type AuditPlan } from "@/app/audits/page"

export const upcomingRenewals = [
  { id: 1, name: "Adobe Creative Cloud", type: "Software", daysLeft: 7, cost: 375000 },
  { id: 2, name: "Figma Enterprise", type: "Cloud Service", daysLeft: 12, cost: 810000 },
  { id: 3, name: "Microsoft 365 E5", type: "Software", daysLeft: 25, cost: 1875000 },
  { id: 4, name: "JetBrains All Products Pack", type: "Software", daysLeft: 28, cost: 133500 },
  { id: 5, name: "Zoom Business", type: "Cloud Service", daysLeft: 35, cost: 180000 },
  { id: 6, name: "Slack Pro", type: "Cloud Service", daysLeft: 40, cost: 225000 },
  { id: 7, name: "GitHub Enterprise", type: "Cloud Service", daysLeft: 55, cost: 630000 },
  { id: 8, name: "Salesforce Sales Cloud", type: "Cloud Service", daysLeft: 60, cost: 1200000 },
  { id: 9, name: "Tableau Creator", type: "Software", daysLeft: 75, cost: 270000 },
  { id: 10, name: "Asana Business", type: "Cloud Service", daysLeft: 89, cost: 330000 },
];

export const assetDistribution = [
  { category: "Tokyo HQ", pcs: 150, smartphones: 120, software: 300, office: 200 },
  { category: "Osaka Branch", pcs: 80, smartphones: 75, software: 150, office: 100 },
  { category: "Fukuoka Branch", pcs: 60, smartphones: 50, software: 120, office: 80 },
  { category: "Sapporo R&D", pcs: 90, smartphones: 40, software: 180, office: 70 },
  { category: "Nagoya Sales", pcs: 50, smartphones: 60, software: 100, office: 60 },
];

export const inventory = {
  pcs: [
    {
      id: "PC001",
      hostname: "TYO-L-SATOT",
      manufacturer: "Dell",
      model: "XPS 15 9530",
      partNumber: "N/A",
      serialNumber: "SN-PC001XYZ",
      formFactor: "Laptop",
      os: "Windows 11 Pro",
      osBit: "64-bit",
      officeSuite: "Microsoft 365 Apps for enterprise",
      softwareLicenseKey: "Windows: XXXX-XXXX-XXXX-XXXX",
      wiredMacAddress: "",
      wiredIpAddress: "",
      wirelessMacAddress: "",
      wirelessIpAddress: "",
      purchaseDate: "2023-05-10",
      purchasePrice: "280000",
      depreciationYears: "4",
      depreciationDept: "Engineering",
      cpu: "Intel Core i7-13700H",
      memory: "32GB",
      location: "Tokyo HQ",
      status: "In Use",
      previousUser: "N/A",
      userId: "佐藤 太郎",
      usageStartDate: "2023-05-15",
      usageEndDate: "",
      carryInOutAgreement: "Signed",
      lastUpdated: "2024-07-01",
      updatedBy: "IT Admin",
      notes: "Docking station included.",
      project: "Project Phoenix",
      notes1: "",
      notes2: "",
      notes3: "",
      notes4: "",
      notes5: "",
    },
    {
      id: "PC002",
      hostname: "OSA-D-SUZUH",
      manufacturer: "HP",
      model: "Z2 Tower G9",
      partNumber: "N/A",
      serialNumber: "SN-PC002ABC",
      formFactor: "Desktop",
      os: "Windows 11 Pro",
      osBit: "64-bit",
      officeSuite: "Microsoft 365 Apps for enterprise",
      softwareLicenseKey: "Windows: YYYY-YYYY-YYYY-YYYY",
      wiredMacAddress: "",
      wiredIpAddress: "",
      wirelessMacAddress: "",
      wirelessIpAddress: "",
      purchaseDate: "2023-03-20",
      purchasePrice: "350000",
      depreciationYears: "5",
      depreciationDept: "Design",
      cpu: "Intel Core i9-13900K",
      memory: "64GB",
      location: "Osaka Branch",
      status: "In Use",
      previousUser: "N/A",
      userId: "鈴木 花子",
      usageStartDate: "2023-03-25",
      usageEndDate: "",
      carryInOutAgreement: "N/A",
      lastUpdated: "2024-06-28",
      updatedBy: "IT Admin",
      notes: "Dual monitor setup.",
      project: "Project Titan",
      notes1: "",
      notes2: "",
      notes3: "",
      notes4: "",
      notes5: "",
    },
    {
      id: "PC003",
      hostname: "FUK-L-TAKAI",
      manufacturer: "Lenovo",
      model: "ThinkPad X1 Carbon Gen 11",
      partNumber: "N/A",
      serialNumber: "SN-PC003DEF",
      formFactor: "Laptop",
      os: "Windows 11 Pro",
      osBit: "64-bit",
      officeSuite: "Microsoft 365 Apps for enterprise",
      softwareLicenseKey: "Windows: ZZZZ-ZZZZ-ZZZZ-ZZZZ",
      wiredMacAddress: "",
      wiredIpAddress: "",
      wirelessMacAddress: "",
      wirelessIpAddress: "",
      purchaseDate: "2023-08-01",
      purchasePrice: "250000",
      depreciationYears: "4",
      depreciationDept: "Sales",
      cpu: "Intel Core i7-1365U",
      memory: "16GB",
      location: "Fukuoka Branch",
      status: "In Use",
      previousUser: "N/A",
      userId: "高橋 一郎",
      usageStartDate: "2023-08-05",
      usageEndDate: "",
      carryInOutAgreement: "Signed",
      lastUpdated: "2024-07-02",
      updatedBy: "IT Admin",
      notes: "",
      project: "Sales Team",
      notes1: "",
      notes2: "",
      notes3: "",
      notes4: "",
      notes5: "",
    },
     {
      id: "PC004",
      hostname: "TYO-L-TANAM",
      manufacturer: "Apple",
      model: "MacBook Pro 16-inch M2 Max",
      partNumber: "N/A",
      serialNumber: "SN-PC004GHI",
      formFactor: "Laptop",
      os: "macOS Sonoma",
      osBit: "64-bit",
      officeSuite: "Microsoft 365 Apps for enterprise",
      softwareLicenseKey: "",
      wiredMacAddress: "",
      wiredIpAddress: "",
      wirelessMacAddress: "",
      wirelessIpAddress: "",
      purchaseDate: "2023-06-15",
      purchasePrice: "450000",
      depreciationYears: "4",
      depreciationDept: "Marketing",
      cpu: "Apple M2 Max",
      memory: "32GB",
      location: "Tokyo HQ",
      status: "In Use",
      previousUser: "N/A",
      userId: "田中 美咲",
      usageStartDate: "2023-06-20",
      usageEndDate: "",
      carryInOutAgreement: "Signed",
      lastUpdated: "2024-07-01",
      updatedBy: "IT Admin",
      notes: "Requires USB-C hub.",
      project: "Marketing",
      notes1: "",
      notes2: "",
      notes3: "",
      notes4: "",
      notes5: "",
    },
    {
      id: "PC005",
      hostname: "SAPPORO-D-WATAK",
      manufacturer: "Custom",
      model: "DevBox 2023",
      partNumber: "N/A",
      serialNumber: "SN-PC005JKL",
      formFactor: "Desktop",
      os: "Ubuntu 22.04 LTS",
      osBit: "64-bit",
      officeSuite: "",
      softwareLicenseKey: "",
      wiredMacAddress: "",
      wiredIpAddress: "",
      wirelessMacAddress: "",
      wirelessIpAddress: "",
      purchaseDate: "2023-01-30",
      purchasePrice: "400000",
      depreciationYears: "5",
      depreciationDept: "Engineering",
      cpu: "AMD Ryzen 9 7950X",
      memory: "128GB",
      location: "Sapporo R&D",
      status: "In Storage",
      previousUser: "N/A",
      userId: "渡辺 健太",
      usageStartDate: "2023-02-05",
      usageEndDate: "",
      carryInOutAgreement: "N/A",
      lastUpdated: "2024-05-15",
      updatedBy: "IT Admin",
      notes: "High-performance build for AI research.",
      project: "Project Phoenix",
      notes1: "",
      notes2: "",
      notes3: "",
      notes4: "",
      notes5: "",
    }
  ],
  monitors: [
    { id: "MON001", model: "Dell U2723QE", size: "27-inch", resolution: "4K", userId: "佐藤 太郎", project: "Project Phoenix", location: "Tokyo HQ", status: "In Use" },
    { id: "MON002", model: "LG 34WK95U-W", size: "34-inch Ultrawide", resolution: "5K2K", userId: "鈴木 花子", project: "Project Titan", location: "Osaka Branch", status: "In Use" },
    { id: "MON003", model: "BenQ PD3220U", size: "32-inch", resolution: "4K", userId: "高橋 一郎", project: "Internal Tools", location: "Fukuoka Branch", status: "In Use" },
    { id: "MON004", model: "Apple Studio Display", size: "27-inch", resolution: "5K", userId: "渡辺 健太", project: "Marketing", location: "Sapporo R&D", status: "In Use" },
    { id: "MON005", model: "Dell U2723QE", size: "27-inch", resolution: "4K", userId: "Unassigned", project: "Unassigned", location: "Tokyo HQ", status: "In Storage" },
  ],
      smartphones: [
      { id: "SP001", model: "iPhone 15 Pro", userId: "佐藤 太郎", project: "Sales Team", location: "Nagoya Sales", assignedDate: "2023-09-20", status: "Active" },
      { id: "SP002", model: "Samsung Galaxy S24", userId: "鈴木 花子", project: "Project Titan", location: "Osaka Branch", assignedDate: "2024-02-01", status: "Active" },
      { id: "SP003", model: "Google Pixel 8", userId: "高橋 一郎", project: "Internal Tools", location: "Fukuoka Branch", assignedDate: "2023-10-15", status: "Active" },
      { id: "SP004", model: "iPhone 15", userId: "田中 美咲", project: "Project Phoenix", location: "Tokyo HQ", assignedDate: "2023-09-20", status: "In Storage" },
      { id: "SP005", model: "Sony Xperia 1 V", userId: "渡辺 健太", project: "Development", location: "Sapporo R&D", assignedDate: "2023-11-15", status: "Active" }
    ],
};

export const masterData = {
  locations: ["Fukuoka Branch", "Nagoya Sales", "Osaka Branch", "Sapporo R&D", "Tokyo HQ", "サーバ室"],
  projects: ["All Infrastructure", "Design", "Design/Dev", "Development", "Internal Tools", "IT", "Marketing", "Marketing Analytics", "Marketing/Design", "Project Phoenix", "Sales Team", "Project Titan", "Unassigned"],
  employees: [
    ...new Set([
        ...inventory.pcs.map(pc => pc.userId),
        ...inventory.monitors.map(m => m.userId),
        ...inventory.smartphones.map(s => s.userId)
    ].filter(Boolean))
  ],
  assetFields: [
    { id: 'field_01', order: 1, systemName: 'id', displayName: '管理番号', dataType: 'Text' as const, visible: true, notes: '一意の資産ID' },
    { id: 'field_08', order: 2, systemName: 'location', displayName: '所在', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_11', order: 3, systemName: 'userId', displayName: '利用者', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_09', order: 4, systemName: 'status', displayName: '状態', dataType: 'Text' as const, visible: true, notes: '例: 使用中, 保管中, 修理中, 廃棄済' },
    { id: 'field_37', order: 5, systemName: 'type', displayName: '資産タイプ', dataType: 'Text' as const, visible: true, notes: '例: pc, monitor, phone, others' },
    { id: 'field_02', order: 6, systemName: 'hostname', displayName: 'ホスト名', dataType: 'Text' as const, visible: true, notes: 'ネットワーク上のPC名' },
    { id: 'field_03', order: 7, systemName: 'manufacturer', displayName: 'メーカー', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_04', order: 8, systemName: 'model', displayName: '機種(M)', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_05', order: 9, systemName: 'partNumber', displayName: '型番(P/N)', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_06', order: 10, systemName: 'serialNumber', displayName: '製造番号(S/N)', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_07', order: 11, systemName: 'formFactor', displayName: '形状（識別子）', dataType: 'Text' as const, visible: true, notes: '例: Laptop, Desktop' },
    { id: 'field_10', order: 12, systemName: 'previousUser', displayName: '旧利用者', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_12', order: 13, systemName: 'os', displayName: 'OS', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_13', order: 14, systemName: 'osBit', displayName: 'OS bit', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_14', order: 15, systemName: 'officeSuite', displayName: 'OFFICE', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_15', order: 16, systemName: 'softwareLicenseKey', displayName: 'soft key', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_16', order: 17, systemName: 'wiredMacAddress', displayName: '有線（MACアドレス）', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_17', order: 18, systemName: 'wiredIpAddress', displayName: '有線 IPアドレス', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_18', order: 19, systemName: 'wirelessMacAddress', displayName: '無線（MACアドレス）', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_19', order: 20, systemName: 'wirelessIpAddress', displayName: '無線 IPアドレス', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_20', order: 21, systemName: 'usageStartDate', displayName: '利用開始日', dataType: 'Date' as const, visible: true, notes: '' },
    { id: 'field_21', order: 22, systemName: 'usageEndDate', displayName: '利用終了日', dataType: 'Date' as const, visible: true, notes: '' },
    { id: 'field_22', order: 23, systemName: 'carryInOutAgreement', displayName: '持出持込誓約', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_23', order: 24, systemName: 'lastUpdated', displayName: '更新日', dataType: 'Date' as const, visible: true, notes: '' },
    { id: 'field_24', order: 25, systemName: 'updatedBy', displayName: '更新者', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_25', order: 26, systemName: 'notes', displayName: '備考', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_26', order: 27, systemName: 'purchaseDate', displayName: '購入日', dataType: 'Date' as const, visible: true, notes: '' },
    { id: 'field_27', order: 28, systemName: 'purchasePrice', displayName: '購入価格（税抜）', dataType: 'Number' as const, visible: true, notes: '' },
    { id: 'field_27b', order: 28.5, systemName: 'purchasePriceTaxIncluded', displayName: '購入価格（税込）', dataType: 'Number' as const, visible: true, notes: '' },
    { id: 'field_28', order: 29, systemName: 'depreciationYears', displayName: '償却年数', dataType: 'Number' as const, visible: true, notes: '' },
    { id: 'field_29', order: 30, systemName: 'depreciationDept', displayName: '償却部署', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_30', order: 31, systemName: 'cpu', displayName: 'CPU', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_31', order: 32, systemName: 'memory', displayName: 'MEM', dataType: 'Text' as const, visible: true, notes: '' },
    { id: 'field_32', order: 33, systemName: 'notes1', displayName: '備考1', dataType: 'Text' as const, visible: true, notes: 'カスタム備考1' },
    { id: 'field_33', order: 34, systemName: 'notes2', displayName: '備考2', dataType: 'Text' as const, visible: true, notes: 'カスタム備考2' },
    { id: 'field_34', order: 35, systemName: 'notes3', displayName: '備考3', dataType: 'Text' as const, visible: true, notes: 'カスタム備考3' },
    { id: 'field_35', order: 36, systemName: 'notes4', displayName: '備考4', dataType: 'Text' as const, visible: true, notes: 'カスタム備考4' },
    { id: 'field_36', order: 37, systemName: 'notes5', displayName: '備考5', dataType: 'Text' as const, visible: true, notes: 'カスタム備考5' },
  ],
};

export const auditPlans: AuditPlan[] = [];

export const loans = [
  { id: 'loan-1', assetId: 'PC001', employeeId: 'EMP001', loanDate: '2024-08-15', expectedReturnDate: '2024-08-20', status: "On Loan" },
  { id: 'loan-2', assetId: 'SP002', employeeId: 'EMP002', loanDate: '2024-07-10', expectedReturnDate: '2024-09-10', status: "On Loan" },
  { id: 'loan-3', assetId: 'MON003', employeeId: 'EMP003', loanDate: '2024-08-01', expectedReturnDate: '2024-08-31', status: "On Loan" },
];

export const fieldIdToSchemaKeyMap: { [key: string]: keyof import('@/lib/schemas/inventory').PcAsset } = {
  'field_01': 'id',
  'field_08': 'location',
  'field_09': 'status',
  'field_37': 'type',
  'field_02': 'hostname',
  'field_03': 'manufacturer',
  'field_04': 'model',
  'field_05': 'partNumber',
  'field_06': 'serialNumber',
  'field_07': 'formFactor',
  'field_10': 'previousUser',
  'field_11': 'userId',
  'field_12': 'os',
  'field_13': 'osBit',
  'field_14': 'officeSuite',
  'field_15': 'softwareLicenseKey',
  'field_16': 'wiredMacAddress',
  'field_17': 'wiredIpAddress',
  'field_18': 'wirelessMacAddress',
  'field_19': 'wirelessIpAddress',
  'field_20': 'usageStartDate',
  'field_21': 'usageEndDate',
  'field_22': 'carryInOutAgreement',
  'field_23': 'lastUpdated',
  'field_24': 'updatedBy',
  'field_25': 'notes',
  'field_26': 'purchaseDate',
  'field_27': 'purchasePrice',
  'field_27b': 'purchasePriceTaxIncluded',
  'field_28': 'depreciationYears',
  'field_29': 'depreciationDept',
  'field_30': 'cpu',
  'field_31': 'memory',
  'field_32': 'notes1',
  'field_33': 'notes2',
  'field_34': 'notes3',
  'field_35': 'notes4',
  'field_36': 'notes5',
};

export const activeSubscriptions = [
  { id: 1, name: "Adobe Creative Cloud", type: "Software", monthlyCost: 37500, project: "Design", location: "Tokyo HQ" },
  { id: 2, name: "Figma Enterprise", type: "Cloud Service", monthlyCost: 81000, project: "Design", location: "Osaka Branch" },
  { id: 3, name: "Microsoft 365 E5", type: "Software", monthlyCost: 187500, project: "All Infrastructure", location: "Tokyo HQ" },
  { id: 4, name: "JetBrains All Products Pack", type: "Software", monthlyCost: 13350, project: "Development", location: "Sapporo R&D" },
  { id: 5, name: "Zoom Business", type: "Cloud Service", monthlyCost: 18000, project: "Internal Tools", location: "Tokyo HQ" },
  { id: 6, name: "Slack Pro", type: "Cloud Service", monthlyCost: 22500, project: "Internal Tools", location: "Osaka Branch" },
  { id: 7, name: "GitHub Enterprise", type: "Cloud Service", monthlyCost: 63000, project: "Development", location: "Sapporo R&D" },
  { id: 8, name: "Salesforce Sales Cloud", type: "Cloud Service", monthlyCost: 120000, project: "Sales Team", location: "Nagoya Sales" },
  { id: 9, name: "Tableau Creator", type: "Software", monthlyCost: 27000, project: "Marketing Analytics", location: "Tokyo HQ" },
  { id: 10, name: "Asana Business", type: "Cloud Service", monthlyCost: 33000, project: "Project Management", location: "Fukuoka Branch" },
  { id: 11, name: "AWS Business", type: "Cloud Service", monthlyCost: 450000, project: "Development", location: "Sapporo R&D" },
  { id: 12, name: "Google Workspace", type: "Cloud Service", monthlyCost: 150000, project: "All Infrastructure", location: "Tokyo HQ" },
  { id: 13, name: "Notion Team", type: "Cloud Service", monthlyCost: 12000, project: "Internal Tools", location: "Osaka Branch" },
  { id: 14, name: "Canva Pro", type: "Cloud Service", monthlyCost: 18000, project: "Marketing", location: "Tokyo HQ" },
  { id: 15, name: "Trello Business", type: "Cloud Service", monthlyCost: 15000, project: "Project Management", location: "Fukuoka Branch" },
];

