version: '3.8'

services:
  # MySQL Database - Simplified
  database:
    image: mysql:8.0
    container_name: mysql_db_simple
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: studio_db
      MYSQL_USER: admin_user
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_simple:/var/lib/mysql
    networks:
      - app-network

  # Laravel Backend
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: laravel_backend_simple
    restart: unless-stopped
    expose:
      - "9000"
    volumes:
      - ./server:/var/www/html
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=studio_db
      - DB_USERNAME=admin_user
      - DB_PASSWORD=admin123
    networks:
      - app-network
    command: >
      bash -c "
        echo 'Waiting for database...' &&
        until nc -z database 3306; do sleep 1; done &&
        echo 'Database ready!' &&
        composer install &&
        php artisan key:generate --force &&
        php artisan migrate --force &&
        php artisan serve --host=0.0.0.0 --port=9000
      "

  # Next.js Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nextjs_frontend_simple
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - node_modules_client_simple:/app/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=https://assetwise.glue-si.com/api
      - NEXT_PUBLIC_GRAPHQL_URL=http://backend:9000/api/graphql
    networks:
      - app-network

volumes:
  mysql_data_simple:
  node_modules_client_simple:

networks:
  app-network:
    driver: bridge
